/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data.java;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author YUDHA_P
 */
public class data extends javax.swing.JFrame {
private static Connection koneksi; //Koneksi
private DefaultTableModel model; //Model Tabel
    /**
     * Creates new form data
     */
    public data() {
        initComponents();
        //buat model tabel / header tabel
model=new DefaultTableModel();
this.jTable1.setModel(model);
model.addColumn("ID");
model.addColumn("Nama");
model.addColumn("Alamat");
model.addColumn("Telepon");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txttelepon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cmbadd = new javax.swing.JButton();
        cmbedit = new javax.swing.JButton();
        cmbdelete = new javax.swing.JButton();
        cmrefresh = new javax.swing.JButton();
        lblkode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel1.setText("BIODATA");

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        jLabel4.setText("Telepon");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Alamat", "Telepon"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        cmbadd.setText("Add");
        cmbadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbaddActionPerformed(evt);
            }
        });

        cmbedit.setText("Edit");
        cmbedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbeditActionPerformed(evt);
            }
        });

        cmbdelete.setText("Delete");
        cmbdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbdeleteActionPerformed(evt);
            }
        });

        cmrefresh.setText("Refresh");
        cmrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmrefreshActionPerformed(evt);
            }
        });

        lblkode.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cmbadd, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbedit, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmrefresh))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtalamat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                    .addComponent(txtnama, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttelepon))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblkode, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblkode)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbadd)
                    .addComponent(cmbedit)
                    .addComponent(cmbdelete)
                    .addComponent(cmrefresh))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private static Connection buka_koneksi() {
        if (koneksi==null) {
            try {
                String url="jdbc:mysql://localhost:3306/data"; //nama database perpustakaan
                String user="root"; //user mysql
                String password=""; //password mysql

                DriverManager.registerDriver(new com.mysql.jdbc.Driver());
                koneksi=DriverManager.getConnection(url,user,password);
            }catch (SQLException t) {
                System.out.println("Error membuat koneksi");
            }
        }
     return koneksi;
    }
    private void cmbdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbdeleteActionPerformed
        // TODO add your handling code here:
        Connection c=buka_koneksi();
         String sqlkode="Delete from data "
                 + "Where ID='"+this.lblkode.getText()+"'";
            try {
               PreparedStatement p2=(PreparedStatement) c.prepareStatement(sqlkode);
               p2.executeUpdate();
               p2.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan "+ex.getMessage());
            }
    }//GEN-LAST:event_cmbdeleteActionPerformed

    private void cmbaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbaddActionPerformed
        // TODO add your handling code here:
        Connection c=buka_koneksi(); //panggil function koneksi
        if("Add".equals(this.cmbadd.getText())) //Jika Button Add teks nya Add
         {
             this.cmbadd.setText("Save"); //Buat Teks Button Add yaitu Save
             this.cmbedit.setText("Cancel");
             this.cmbdelete.enable(false);
             this.cmrefresh.enable(false);
             this.lblkode.setText("0"); //Kosongkan Nilai LabelKode
             this.txtnama.setText("");
             this.txtalamat.setText("");
             this.txttelepon.setText("");

         }else if("Save".equals(this.cmbadd.getText()))
         {
             //bikin sql query tambah data
             String sqlkode="Insert into data (`nama`,`alamat`,`tlp`) "
                     + "values ('"+this.txtnama.getText()+"',"
                     + "'"+this.txtalamat.getText()+"',"
                     + "'"+this.txttelepon.getText()+"')";
            try { //jalankan query tersebut
               PreparedStatement p2=(PreparedStatement) c.prepareStatement(sqlkode);
               p2.executeUpdate();
               p2.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan "+ex.getMessage());
            }
             this.cmbadd.setText("Add");
             this.cmbedit.setText("Edit");
             this.cmbdelete.enable(true);
             this.cmrefresh.enable(true);
         }else if("Update".equals(this.cmbadd.getText()))
         {//bikin query update data
             String sqlkode="Update data SET `nama`='"+this.txtnama.getText()+"',"
                     + "`alamat`='"+this.txtalamat.getText()+"',"
                     + "`tlp`='"+this.txttelepon.getText()+"' "
                     + "Where ID='"+this.lblkode.getText()+"'";
            try {
               PreparedStatement p2=(PreparedStatement) c.prepareStatement(sqlkode);
               p2.executeUpdate();
               p2.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan "+ex.getMessage());
            }
             this.cmbadd.setText("Add");
             this.cmbedit.setText("Edit");
             this.cmbdelete.enable(true);
             this.cmrefresh.enable(true);
         }
    }//GEN-LAST:event_cmbaddActionPerformed

    private void cmbeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbeditActionPerformed
        // TODO add your handling code here:
        if("Edit".equals(this.cmbedit.getText()))
         {
             this.cmbadd.setText("Update");
             this.cmbedit.setText("Cancel");
             this.cmbdelete.enable(false);
             this.cmrefresh.enable(false);
         }else if("Cancel".equals(this.cmbedit.getText()))
         {
             this.cmbadd.setText("Add");
             this.cmbedit.setText("Edit");
             this.cmbdelete.enable(true);
             this.cmrefresh.enable(true);
         }
    }//GEN-LAST:event_cmbeditActionPerformed

    private void cmrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmrefreshActionPerformed
        // TODO add your handling code here:
        ambil_data_tabel();

    }//GEN-LAST:event_cmrefreshActionPerformed
private void ambil_data_tabel()
{
    model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c=buka_koneksi();
            Statement s= c.createStatement();
            String sql="Select * from data";
            ResultSet r=s.executeQuery(sql);

            while (r.next()) {
                Object[] o=new Object[4];
                o[0]=r.getString("id");
                o[1]=r.getString("nama");
                o[2]=r.getString("alamat");
                o[3]=r.getString("tlp");


                model.addRow(o);
            }
            r.close();
            s.close();
            ambil_tabel_klik();
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan "+e.getMessage());
        }
}

private void ambil_tabel_klik()
{
    int i=this.jTable1.getSelectedRow();

        if(i==-1)
        {
            return;
        }
        String id=(String) model.getValueAt(i, 0);
        this.lblkode.setText(id);
        String nama=(String) model.getValueAt(i, 1);
        this.txtnama.setText(nama);
        String alamat=(String) model.getValueAt(i, 2);
        this.txtalamat.setText(alamat);
        String tlp=(String) model.getValueAt(i, 3);
        this.txttelepon.setText(tlp);
}
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         this.ambil_tabel_klik();
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new data().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbadd;
    private javax.swing.JButton cmbdelete;
    private javax.swing.JButton cmbedit;
    private javax.swing.JButton cmrefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblkode;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttelepon;
    // End of variables declaration//GEN-END:variables

